<a href="https://colab.research.google.com/github/naomiburgess/QM2group15/blob/main/Source1_with_geometry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('seaborn')

In [16]:
#Install the geopandas module
!pip install geopandas

#Uninstall any existing version; forcing Yes
!pip uninstall --yes pysal

#Install newest branch
!pip install pysal == 2.0.0

Requirement already satisfied: geopandas in /usr/local/lib/python3.6/dist-packages (0.8.1)
Requirement already satisfied: fiona in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.8.18)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.1.5)
Requirement already satisfied: shapely in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.7.1)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from geopandas) (3.0.0.post1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (0.7.1)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (1.15.0)
Requirement already satisfied: munch in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (2.5.0)
Requirement already satisfied: click<8,>=4.0 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (7.1.2)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (1.1.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (2020.12.5)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (20.3.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (1.19.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (2.8.0)
Uninstalling pysal-2.3.0:
  Successfully uninstalled pysal-2.3.0
ERROR: Invalid requirement: '=='

In [17]:
!pip install pysal
import geopandas as gp
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import pylab
import descartes

%matplotlib inline

plt.style.use('ggplot')
pylab.rcParams['figure.figsize'] = (20., 16.)

Processing /root/.cache/pip/wheels/ec/51/8f/4fd7e7088448f99c3a26c2cf434b60ba18b6fef695dd72f439/pysal-2.3.0-cp36-none-any.whl
Requirement already satisfied: spreg>=1.1.1 in /usr/local/lib/python3.6/dist-packages (from pysal) (1.1.2.post1)
Requirement already satisfied: spint>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from pysal) (1.0.7)
Requirement already satisfied: tobler>=0.3.1 in /usr/local/lib/python3.6/dist-packages (from pysal) (0.5.4)
Requirement already satisfied: splot>=1.1.3 in /usr/local/lib/python3.6/dist-packages (from pysal) (1.1.3)
Requirement already satisfied: python-dateutil<=2.8.0 in /usr/local/lib/python3.6/dist-packages (from pysal) (2.8.0)
Requirement already satisfied: segregation>=1.3.0 in /usr/local/lib/python3.6/dist-packages (from pysal) (1.5.0)
Requirement already satisfied: pytest-cov in /usr/local/lib/python3.6/dist-packages (from pysal) (2.10.1)
Requirement already satisfied: inequality>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from pysal) (1.0.0)
Requirement already satisfied: pytest in /usr/local/lib/python3.6/dist-packages (from pysal) (3.6.4)
Requirement already satisfied: esda>=2.3.1 in /usr/local/lib/python3.6/dist-packages (from pysal) (2.3.5)
Requirement already satisfied: mgwr>=2.1.1 in /usr/local/lib/python3.6/dist-packages (from pysal) (2.1.2)
Requirement already satisfied: libpysal>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from pysal) (4.3.0)
Requirement already satisfied: spglm>=1.0.7 in /usr/local/lib/python3.6/dist-packages (from pysal) (1.0.8)
Requirement already satisfied: urllib3<1.25 in /usr/local/lib/python3.6/dist-packages (from pysal) (1.24.3)
Requirement already satisfied: coverage in /usr/local/lib/python3.6/dist-packages (from pysal) (3.7.1)
Requirement already satisfied: access>=1.1.1 in /usr/local/lib/python3.6/dist-packages (from pysal) (1.1.3)
Requirement already satisfied: spvcm==0.3.0 in /usr/local/lib/python3.6/dist-packages (from pysal) (0.3.0)
Requirement already satisfied: giddy>=2.3.3 in /usr/local/lib/python3.6/dist-packages (from pysal) (2.3.3)
Requirement already satisfied: mapclassify>=2.3.0 in /usr/local/lib/python3.6/dist-packages (from pysal) (2.4.2)
Requirement already satisfied: pointpats>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from pysal) (2.2.0)
Requirement already satisfied: spaghetti>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pysal) (1.5.3)
Requirement already satisfied: scipy>=0.11 in /usr/local/lib/python3.6/dist-packages (from spreg>=1.1.1->pysal) (1.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from spreg>=1.1.1->pysal) (1.1.5)
Requirement already satisfied: numpy>=1.3 in /usr/local/lib/python3.6/dist-packages (from spreg>=1.1.1->pysal) (1.19.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from tobler>=0.3.1->pysal) (4.41.1)
Requirement already satisfied: rasterstats in /usr/local/lib/python3.6/dist-packages (from tobler>=0.3.1->pysal) (0.15.0)
Requirement already satisfied: rasterio in /usr/local/lib/python3.6/dist-packages (from tobler>=0.3.1->pysal) (1.1.8)
Requirement already satisfied: geopandas in /usr/local/lib/python3.6/dist-packages (from tobler>=0.3.1->pysal) (0.8.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.6/dist-packages (from tobler>=0.3.1->pysal) (0.10.2)
Requirement already satisfied: descartes in /usr/local/lib/python3.6/dist-packages (from splot>=1.1.3->pysal) (1.1.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from splot>=1.1.3->pysal) (3.2.2)
Requirement already satisfied: seaborn in /usr/local/lib/python3.6/dist-packages (from splot>=1.1.3->pysal) (0.11.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil<=2.8.0->pysal) (1.15.0)
Requirement already satisfied: scikit-learn>=0.21.3 in /usr/local/lib/python3.6/dist-packages (from segregation>=1.3.0->pysal) (0.22.2.post1)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.6/dist-packages (from pytest->pysal) (0.7.1)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest->pysal) (1.10.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.6/dist-packages (from pytest->pysal) (1.4.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from pytest->pysal) (51.0.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from pytest->pysal) (8.6.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest->pysal) (20.3.0)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from libpysal>=4.3.0->pysal) (2.23.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.6/dist-packages (from libpysal>=4.3.0->pysal) (4.6.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/dist-packages (from libpysal>=4.3.0->pysal) (2.11.2)
Requirement already satisfied: quantecon>=0.4.7 in /usr/local/lib/python3.6/dist-packages (from giddy>=2.3.3->pysal) (0.4.8)
Requirement already satisfied: networkx in /usr/local/lib/python3.6/dist-packages (from mapclassify>=2.3.0->pysal) (2.5)
Requirement already satisfied: opencv-contrib-python>=4.2.0 in /usr/local/lib/python3.6/dist-packages (from pointpats>=2.2.0->pysal) (4.5.1.48)
Requirement already satisfied: rtree in /usr/local/lib/python3.6/dist-packages (from spaghetti>=1.5.0->pysal) (0.9.7)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->spreg>=1.1.1->pysal) (2018.9)
Requirement already satisfied: fiona in /usr/local/lib/python3.6/dist-packages (from rasterstats->tobler>=0.3.1->pysal) (1.8.18)
Requirement already satisfied: shapely in /usr/local/lib/python3.6/dist-packages (from rasterstats->tobler>=0.3.1->pysal) (1.7.1)
Requirement already satisfied: affine<3.0 in /usr/local/lib/python3.6/dist-packages (from rasterstats->tobler>=0.3.1->pysal) (2.3.0)
Requirement already satisfied: simplejson in /usr/local/lib/python3.6/dist-packages (from rasterstats->tobler>=0.3.1->pysal) (3.17.2)
Requirement already satisfied: cligj>=0.4 in /usr/local/lib/python3.6/dist-packages (from rasterstats->tobler>=0.3.1->pysal) (0.7.1)
Requirement already satisfied: click-plugins in /usr/local/lib/python3.6/dist-packages (from rasterio->tobler>=0.3.1->pysal) (1.1.1)
Requirement already satisfied: snuggs>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from rasterio->tobler>=0.3.1->pysal) (1.4.7)
Requirement already satisfied: click<8,>=4.0 in /usr/local/lib/python3.6/dist-packages (from rasterio->tobler>=0.3.1->pysal) (7.1.2)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from geopandas->tobler>=0.3.1->pysal) (3.0.0.post1)
Requirement already satisfied: patsy>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from statsmodels->tobler>=0.3.1->pysal) (0.5.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->splot>=1.1.3->pysal) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->splot>=1.1.3->pysal) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->splot>=1.1.3->pysal) (1.3.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.21.3->segregation>=1.3.0->pysal) (1.0.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->libpysal>=4.3.0->pysal) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->libpysal>=4.3.0->pysal) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->libpysal>=4.3.0->pysal) (2020.12.5)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2->libpysal>=4.3.0->pysal) (1.1.1)
Requirement already satisfied: numba>=0.38 in /usr/local/lib/python3.6/dist-packages (from quantecon>=0.4.7->giddy>=2.3.3->pysal) (0.48.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.6/dist-packages (from quantecon>=0.4.7->giddy>=2.3.3->pysal) (1.1.1)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from networkx->mapclassify>=2.3.0->pysal) (4.4.2)
Requirement already satisfied: munch in /usr/local/lib/python3.6/dist-packages (from fiona->rasterstats->tobler>=0.3.1->pysal) (2.5.0)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /usr/local/lib/python3.6/dist-packages (from numba>=0.38->quantecon>=0.4.7->giddy>=2.3.3->pysal) (0.31.0)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.6/dist-packages (from sympy->quantecon>=0.4.7->giddy>=2.3.3->pysal) (1.1.0)
Installing collected packages: pysal
Successfully installed pysal-2.3.0

In [18]:
data_path = "London_Ward.shp"

# londonWards = gp.GeoDataFrame.from_file(data_path)

londonWards = gp.read_file(data_path)

londonWards.head()

                     NAME  ...                                           geometry
0       Chessington South  ...  POLYGON ((516401.600 160201.800, 516407.300 16...
1  Tolworth and Hook Rise  ...  POLYGON ((517829.600 165447.100, 517837.100 16...
2              Berrylands  ...  POLYGON ((518107.500 167303.400, 518114.300 16...
3               Alexandra  ...  POLYGON ((520480.000 166909.800, 520490.700 16...
4                Beverley  ...  POLYGON ((522071.000 168144.900, 522063.900 16...

[5 rows x 8 columns]

In [19]:
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Kingston upon Thames'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Croydon'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'City of London'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Bromley'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Barking and Dagenham'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'City of Westminster'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Hounslow'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Newham'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Hackney'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Islington'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Ealing'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Haringey'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Havering'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Tower Hamlets'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Hillingdon'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Harrow'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Brent'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Barnet'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Lambeth'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Southwark'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Lewisham'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Greenwich'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Bexley'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Enfield'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Waltham Forest'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Redbridge'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Sutton'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Richmond upon Thames'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Merton'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Wandsworth'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Hammersmith and Fulham'], inplace = True)
londonWards.drop(londonWards.index[londonWards['BOROUGH'] == 'Westminster'], inplace = True)

londonWards

                               NAME  ...                                           geometry
460                        Cremorne  ...  POLYGON ((526027.600 177216.200, 526067.100 17...
461                         Holland  ...  POLYGON ((525426.700 179502.900, 525404.600 17...
462                         Norland  ...  POLYGON ((523600.100 180701.400, 523604.600 18...
463                        Golborne  ...  POLYGON ((524230.900 181514.300, 524193.200 18...
464                       Redcliffe  ...  POLYGON ((525674.800 178424.600, 525683.100 17...
465                         Stanley  ...  POLYGON ((526523.200 178032.900, 526685.800 17...
466                  Royal Hospital  ...  POLYGON ((527496.500 178268.400, 527559.800 17...
467                        Brompton  ...  POLYGON ((526757.200 178291.800, 526667.200 17...
468                        Abingdon  ...  POLYGON ((525669.000 178860.700, 525604.000 17...
469                       Pembridge  ...  POLYGON ((524551.300 180815.200, 524554.000 18...
470                   Notting Barns  ...  POLYGON ((524368.200 181197.500, 524344.400 18...
471                        Colville  ...  POLYGON ((524368.200 181197.500, 524346.700 18...
472                     St. Charles  ...  POLYGON ((524230.900 181514.300, 524030.300 18...
473                    Earl's Court  ...  POLYGON ((524933.500 178522.200, 524954.000 17...
474                      Courtfield  ...  POLYGON ((525752.600 178859.100, 525810.400 17...
475                    Queen's Gate  ...  POLYGON ((526505.200 178946.200, 526445.600 17...
476                       Hans Town  ...  POLYGON ((527162.300 178408.800, 527158.400 17...
477                         Campden  ...  POLYGON ((525426.700 179502.900, 525425.600 17...
498                   Swiss Cottage  ...  POLYGON ((527370.800 183470.700, 527255.200 18...
499                        Highgate  ...  POLYGON ((526683.200 187383.700, 526684.400 18...
500                         Kilburn  ...  POLYGON ((524780.800 184464.200, 524791.200 18...
501                      Bloomsbury  ...  POLYGON ((528891.100 182192.600, 528900.900 18...
502       Holborn and Covent Garden  ...  POLYGON ((530397.000 182121.800, 530480.500 18...
503     St. Pancras and Somers Town  ...  POLYGON ((529096.900 183713.400, 529224.100 18...
504  Camden Town with Primrose Hill  ...  POLYGON ((527676.900 183645.500, 527681.000 18...
505                      Cantelowes  ...  POLYGON ((530121.000 184134.200, 530065.000 18...
506                    King's Cross  ...  POLYGON ((530326.100 182983.300, 530364.800 18...
507                   Fortune Green  ...  POLYGON ((524651.100 184647.000, 524612.500 18...
508           Frognal and Fitzjohns  ...  POLYGON ((525534.300 186427.800, 525556.300 18...
509                      Gospel Oak  ...  POLYGON ((528480.500 185441.400, 528489.700 18...
510                  Hampstead Town  ...  POLYGON ((526902.100 185000.200, 526863.500 18...
511                    Kentish Town  ...  POLYGON ((529153.600 185861.400, 529222.700 18...
512                  West Hampstead  ...  POLYGON ((524651.100 184647.000, 524735.300 18...
513                         Belsize  ...  POLYGON ((527541.800 184205.300, 527538.000 18...
514                      Haverstock  ...  POLYGON ((527679.500 184261.400, 527671.500 18...
515                   Regent's Park  ...  POLYGON ((528891.100 182192.600, 528891.400 18...

[36 rows x 8 columns]

In [20]:
df = pd.DataFrame(londonWards)
df

                               NAME  ...                                           geometry
460                        Cremorne  ...  POLYGON ((526027.600 177216.200, 526067.100 17...
461                         Holland  ...  POLYGON ((525426.700 179502.900, 525404.600 17...
462                         Norland  ...  POLYGON ((523600.100 180701.400, 523604.600 18...
463                        Golborne  ...  POLYGON ((524230.900 181514.300, 524193.200 18...
464                       Redcliffe  ...  POLYGON ((525674.800 178424.600, 525683.100 17...
465                         Stanley  ...  POLYGON ((526523.200 178032.900, 526685.800 17...
466                  Royal Hospital  ...  POLYGON ((527496.500 178268.400, 527559.800 17...
467                        Brompton  ...  POLYGON ((526757.200 178291.800, 526667.200 17...
468                        Abingdon  ...  POLYGON ((525669.000 178860.700, 525604.000 17...
469                       Pembridge  ...  POLYGON ((524551.300 180815.200, 524554.000 18...
470                   Notting Barns  ...  POLYGON ((524368.200 181197.500, 524344.400 18...
471                        Colville  ...  POLYGON ((524368.200 181197.500, 524346.700 18...
472                     St. Charles  ...  POLYGON ((524230.900 181514.300, 524030.300 18...
473                    Earl's Court  ...  POLYGON ((524933.500 178522.200, 524954.000 17...
474                      Courtfield  ...  POLYGON ((525752.600 178859.100, 525810.400 17...
475                    Queen's Gate  ...  POLYGON ((526505.200 178946.200, 526445.600 17...
476                       Hans Town  ...  POLYGON ((527162.300 178408.800, 527158.400 17...
477                         Campden  ...  POLYGON ((525426.700 179502.900, 525425.600 17...
498                   Swiss Cottage  ...  POLYGON ((527370.800 183470.700, 527255.200 18...
499                        Highgate  ...  POLYGON ((526683.200 187383.700, 526684.400 18...
500                         Kilburn  ...  POLYGON ((524780.800 184464.200, 524791.200 18...
501                      Bloomsbury  ...  POLYGON ((528891.100 182192.600, 528900.900 18...
502       Holborn and Covent Garden  ...  POLYGON ((530397.000 182121.800, 530480.500 18...
503     St. Pancras and Somers Town  ...  POLYGON ((529096.900 183713.400, 529224.100 18...
504  Camden Town with Primrose Hill  ...  POLYGON ((527676.900 183645.500, 527681.000 18...
505                      Cantelowes  ...  POLYGON ((530121.000 184134.200, 530065.000 18...
506                    King's Cross  ...  POLYGON ((530326.100 182983.300, 530364.800 18...
507                   Fortune Green  ...  POLYGON ((524651.100 184647.000, 524612.500 18...
508           Frognal and Fitzjohns  ...  POLYGON ((525534.300 186427.800, 525556.300 18...
509                      Gospel Oak  ...  POLYGON ((528480.500 185441.400, 528489.700 18...
510                  Hampstead Town  ...  POLYGON ((526902.100 185000.200, 526863.500 18...
511                    Kentish Town  ...  POLYGON ((529153.600 185861.400, 529222.700 18...
512                  West Hampstead  ...  POLYGON ((524651.100 184647.000, 524735.300 18...
513                         Belsize  ...  POLYGON ((527541.800 184205.300, 527538.000 18...
514                      Haverstock  ...  POLYGON ((527679.500 184261.400, 527671.500 18...
515                   Regent's Park  ...  POLYGON ((528891.100 182192.600, 528891.400 18...

[36 rows x 8 columns]

In [28]:
df.sort_values(by=["BOROUGH", "NAME"], inplace = True)
df

                               NAME  ...                                           geometry
513                         Belsize  ...  POLYGON ((527541.800 184205.300, 527538.000 18...
501                      Bloomsbury  ...  POLYGON ((528891.100 182192.600, 528900.900 18...
504  Camden Town with Primrose Hill  ...  POLYGON ((527676.900 183645.500, 527681.000 18...
505                      Cantelowes  ...  POLYGON ((530121.000 184134.200, 530065.000 18...
507                   Fortune Green  ...  POLYGON ((524651.100 184647.000, 524612.500 18...
508           Frognal and Fitzjohns  ...  POLYGON ((525534.300 186427.800, 525556.300 18...
509                      Gospel Oak  ...  POLYGON ((528480.500 185441.400, 528489.700 18...
510                  Hampstead Town  ...  POLYGON ((526902.100 185000.200, 526863.500 18...
514                      Haverstock  ...  POLYGON ((527679.500 184261.400, 527671.500 18...
499                        Highgate  ...  POLYGON ((526683.200 187383.700, 526684.400 18...
502       Holborn and Covent Garden  ...  POLYGON ((530397.000 182121.800, 530480.500 18...
511                    Kentish Town  ...  POLYGON ((529153.600 185861.400, 529222.700 18...
500                         Kilburn  ...  POLYGON ((524780.800 184464.200, 524791.200 18...
506                    King's Cross  ...  POLYGON ((530326.100 182983.300, 530364.800 18...
515                   Regent's Park  ...  POLYGON ((528891.100 182192.600, 528891.400 18...
503     St. Pancras and Somers Town  ...  POLYGON ((529096.900 183713.400, 529224.100 18...
498                   Swiss Cottage  ...  POLYGON ((527370.800 183470.700, 527255.200 18...
512                  West Hampstead  ...  POLYGON ((524651.100 184647.000, 524735.300 18...
468                        Abingdon  ...  POLYGON ((525669.000 178860.700, 525604.000 17...
467                        Brompton  ...  POLYGON ((526757.200 178291.800, 526667.200 17...
477                         Campden  ...  POLYGON ((525426.700 179502.900, 525425.600 17...
471                        Colville  ...  POLYGON ((524368.200 181197.500, 524346.700 18...
474                      Courtfield  ...  POLYGON ((525752.600 178859.100, 525810.400 17...
460                        Cremorne  ...  POLYGON ((526027.600 177216.200, 526067.100 17...
473                    Earl's Court  ...  POLYGON ((524933.500 178522.200, 524954.000 17...
463                        Golborne  ...  POLYGON ((524230.900 181514.300, 524193.200 18...
476                       Hans Town  ...  POLYGON ((527162.300 178408.800, 527158.400 17...
461                         Holland  ...  POLYGON ((525426.700 179502.900, 525404.600 17...
462                         Norland  ...  POLYGON ((523600.100 180701.400, 523604.600 18...
470                   Notting Barns  ...  POLYGON ((524368.200 181197.500, 524344.400 18...
469                       Pembridge  ...  POLYGON ((524551.300 180815.200, 524554.000 18...
475                    Queen's Gate  ...  POLYGON ((526505.200 178946.200, 526445.600 17...
464                       Redcliffe  ...  POLYGON ((525674.800 178424.600, 525683.100 17...
466                  Royal Hospital  ...  POLYGON ((527496.500 178268.400, 527559.800 17...
472                     St. Charles  ...  POLYGON ((524230.900 181514.300, 524030.300 18...
465                         Stanley  ...  POLYGON ((526523.200 178032.900, 526685.800 17...

[36 rows x 8 columns]

In [39]:
df = df.reset_index()
del df['index']
df

                              NAME  ...                                           geometry
0                          Belsize  ...  POLYGON ((527541.800 184205.300, 527538.000 18...
1                       Bloomsbury  ...  POLYGON ((528891.100 182192.600, 528900.900 18...
2   Camden Town with Primrose Hill  ...  POLYGON ((527676.900 183645.500, 527681.000 18...
3                       Cantelowes  ...  POLYGON ((530121.000 184134.200, 530065.000 18...
4                    Fortune Green  ...  POLYGON ((524651.100 184647.000, 524612.500 18...
5            Frognal and Fitzjohns  ...  POLYGON ((525534.300 186427.800, 525556.300 18...
6                       Gospel Oak  ...  POLYGON ((528480.500 185441.400, 528489.700 18...
7                   Hampstead Town  ...  POLYGON ((526902.100 185000.200, 526863.500 18...
8                       Haverstock  ...  POLYGON ((527679.500 184261.400, 527671.500 18...
9                         Highgate  ...  POLYGON ((526683.200 187383.700, 526684.400 18...
10       Holborn and Covent Garden  ...  POLYGON ((530397.000 182121.800, 530480.500 18...
11                    Kentish Town  ...  POLYGON ((529153.600 185861.400, 529222.700 18...
12                         Kilburn  ...  POLYGON ((524780.800 184464.200, 524791.200 18...
13                    King's Cross  ...  POLYGON ((530326.100 182983.300, 530364.800 18...
14                   Regent's Park  ...  POLYGON ((528891.100 182192.600, 528891.400 18...
15     St. Pancras and Somers Town  ...  POLYGON ((529096.900 183713.400, 529224.100 18...
16                   Swiss Cottage  ...  POLYGON ((527370.800 183470.700, 527255.200 18...
17                  West Hampstead  ...  POLYGON ((524651.100 184647.000, 524735.300 18...
18                        Abingdon  ...  POLYGON ((525669.000 178860.700, 525604.000 17...
19                        Brompton  ...  POLYGON ((526757.200 178291.800, 526667.200 17...
20                         Campden  ...  POLYGON ((525426.700 179502.900, 525425.600 17...
21                        Colville  ...  POLYGON ((524368.200 181197.500, 524346.700 18...
22                      Courtfield  ...  POLYGON ((525752.600 178859.100, 525810.400 17...
23                        Cremorne  ...  POLYGON ((526027.600 177216.200, 526067.100 17...
24                    Earl's Court  ...  POLYGON ((524933.500 178522.200, 524954.000 17...
25                        Golborne  ...  POLYGON ((524230.900 181514.300, 524193.200 18...
26                       Hans Town  ...  POLYGON ((527162.300 178408.800, 527158.400 17...
27                         Holland  ...  POLYGON ((525426.700 179502.900, 525404.600 17...
28                         Norland  ...  POLYGON ((523600.100 180701.400, 523604.600 18...
29                   Notting Barns  ...  POLYGON ((524368.200 181197.500, 524344.400 18...
30                       Pembridge  ...  POLYGON ((524551.300 180815.200, 524554.000 18...
31                    Queen's Gate  ...  POLYGON ((526505.200 178946.200, 526445.600 17...
32                       Redcliffe  ...  POLYGON ((525674.800 178424.600, 525683.100 17...
33                  Royal Hospital  ...  POLYGON ((527496.500 178268.400, 527559.800 17...
34                     St. Charles  ...  POLYGON ((524230.900 181514.300, 524030.300 18...
35                         Stanley  ...  POLYGON ((526523.200 178032.900, 526685.800 17...

[36 rows x 8 columns]

In [22]:
londonWards = londonWards.to_csv("Shapefile.csv")

In [40]:
data = "Source1.csv"
ward_data = pd.read_csv(data)
ward_data
ward_data = ward_data.reset_index()
del ward_data['index']
ward_data

    Unnamed: 0  ... Average Public Transport Accessibility score - 2014
0          103  ...                                                4.2
1          104  ...                                                8.0
2          105  ...                                                5.4
3          106  ...                                                4.9
4          107  ...                                                4.8
5          108  ...                                                4.8
6          109  ...                                                4.1
7          110  ...                                                4.0
8          111  ...                                                4.7
9          112  ...                                                3.9
10         113  ...                                                7.9
11         114  ...                                                5.7
12         115  ...                                                5.5
13         116  ...                                                7.8
14         117  ...                                                6.8
15         118  ...                                                7.1
16         119  ...                                                6.2
17         120  ...                                                6.0
18         357  ...                                                6.5
19         358  ...                                                6.8
20         359  ...                                                6.8
21         360  ...                                                5.4
22         361  ...                                                6.9
23         362  ...                                                4.7
24         363  ...                                                7.0
25         364  ...                                                4.5
26         365  ...                                                6.6
27         366  ...                                                6.0
28         367  ...                                                5.4
29         368  ...                                                4.2
30         369  ...                                                7.0
31         370  ...                                                6.0
32         371  ...                                                6.2
33         372  ...                                                5.0
34         373  ...                                                3.8
35         374  ...                                                5.6

[36 rows x 8 columns]

In [46]:
final = ward_data.join(df)
final

    Unnamed: 0  ...                                           geometry
0          103  ...  POLYGON ((527541.800 184205.300, 527538.000 18...
1          104  ...  POLYGON ((528891.100 182192.600, 528900.900 18...
2          105  ...  POLYGON ((527676.900 183645.500, 527681.000 18...
3          106  ...  POLYGON ((530121.000 184134.200, 530065.000 18...
4          107  ...  POLYGON ((524651.100 184647.000, 524612.500 18...
5          108  ...  POLYGON ((525534.300 186427.800, 525556.300 18...
6          109  ...  POLYGON ((528480.500 185441.400, 528489.700 18...
7          110  ...  POLYGON ((526902.100 185000.200, 526863.500 18...
8          111  ...  POLYGON ((527679.500 184261.400, 527671.500 18...
9          112  ...  POLYGON ((526683.200 187383.700, 526684.400 18...
10         113  ...  POLYGON ((530397.000 182121.800, 530480.500 18...
11         114  ...  POLYGON ((529153.600 185861.400, 529222.700 18...
12         115  ...  POLYGON ((524780.800 184464.200, 524791.200 18...
13         116  ...  POLYGON ((530326.100 182983.300, 530364.800 18...
14         117  ...  POLYGON ((528891.100 182192.600, 528891.400 18...
15         118  ...  POLYGON ((529096.900 183713.400, 529224.100 18...
16         119  ...  POLYGON ((527370.800 183470.700, 527255.200 18...
17         120  ...  POLYGON ((524651.100 184647.000, 524735.300 18...
18         357  ...  POLYGON ((525669.000 178860.700, 525604.000 17...
19         358  ...  POLYGON ((526757.200 178291.800, 526667.200 17...
20         359  ...  POLYGON ((525426.700 179502.900, 525425.600 17...
21         360  ...  POLYGON ((524368.200 181197.500, 524346.700 18...
22         361  ...  POLYGON ((525752.600 178859.100, 525810.400 17...
23         362  ...  POLYGON ((526027.600 177216.200, 526067.100 17...
24         363  ...  POLYGON ((524933.500 178522.200, 524954.000 17...
25         364  ...  POLYGON ((524230.900 181514.300, 524193.200 18...
26         365  ...  POLYGON ((527162.300 178408.800, 527158.400 17...
27         366  ...  POLYGON ((525426.700 179502.900, 525404.600 17...
28         367  ...  POLYGON ((523600.100 180701.400, 523604.600 18...
29         368  ...  POLYGON ((524368.200 181197.500, 524344.400 18...
30         369  ...  POLYGON ((524551.300 180815.200, 524554.000 18...
31         370  ...  POLYGON ((526505.200 178946.200, 526445.600 17...
32         371  ...  POLYGON ((525674.800 178424.600, 525683.100 17...
33         372  ...  POLYGON ((527496.500 178268.400, 527559.800 17...
34         373  ...  POLYGON ((524230.900 181514.300, 524030.300 18...
35         374  ...  POLYGON ((526523.200 178032.900, 526685.800 17...

[36 rows x 16 columns]

In [47]:
final.to_csv("Source1 with geometry.csv")